# 00 - Getting started with Tensorflow

## 1. Introduction to Deep Learning

### What is deep learning?

Artificial intelligence is a field that is trying to get a computer to think for itself. Then Machine learning is turning things (data) into number and <b>finding patterns</b> in those numbers. Deep learning is a subfield of machine Learning. 

<center><img rel="slide ML vs DL" src="images/00-ml-vs-dl.png" heigth=200px width=600px></center>

### Why use deep learning?

<b>Better reason :</b> For a complex problem, can you think of all the rules you'd have to code? Probably not... For example driving a car requires to follow a lot of rules (signs, pedestrian, other cars...)

**When use machine learning ?**

- rule 1 of Google's Machine Learning Handbook: "If you can build a ***simple rule-based*** system that doesn't require machine learning, do that."



### What deep learning is good for ?


- **Problems with long lists of rules** : when the traditional approach fails, machine learning/deep learning may help.
- **Continually changing environments** : deep learning can adapt("learn") to new scenarios.
- **Discovering insights within large collections of data** : can you imagine trying to hand-craft rules for what 101 different kinds of food look like?

### What deep learning is not good for ?


- **When you need explainability** : the patterns learned by a deep learning model are typically uninterpretable by a human.
- **When the traditional approach is a better option** : if you can accomplish what you need with a simple rule-based system.
- **When errors are unacceptable** : since the outputs of deep learning model aren't always predictable.
- **When you don't have much data** : deep learning models usually require a fairly amount of data to produce great results

### What are neural networks?

**Examples of uses :**

<center><img rel="slide ML vs DL" src="images/00-neural-networks.png" heigth=200px width=800px></center>


**Anatomy of Neural Networks :**

<center><img rel="slide ML vs DL" src="images/00-anatomy-neural-networks.png" heigth=200px width=800px></center>

### What is deep learning already being used for?

<center><img rel="slide ML vs DL" src="images/00-deeplearning-use-cases.png" heigth=200px width=800px></center>

## 2. Tensorflow Fundamentals

### What is Tensorflow?

`Tensorflow` is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

### Why use TensorFlow?

Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as Tensorflow. This is because it contains many of the most common machine learning functions we'll want to use.

### Introduction to Tensors

`Tensors` are kind of Numpy arrays.

You can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:
- It could be numbers themselves (using tensors to represent the price of house).
- It could be an image (using tensors to represent the pixels of an image).
- It could be text (using tensors to represent words).
- Or it could be some other form of information (or data) you want to represent with numbers.

The main difference between tensors and NumPy arrays is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).
The benefit of being able to run on GPUs and TPUs is faster computation. This means if we wanted to find patterns in the numerical representations of our data, we can find them faster using GPUs and TPUs.

In [1]:
# import TensorFlow

import tensorflow as tf
print (tf.__version__) # find the version number

2.8.0


### Creating Tensors with `tf.constant()`

In [2]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
# Check the dimension of our matrix
matrix.ndim

2

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype. This is known as 32-bit precision.

In [8]:
# Create another matrix and define the datatype

another_matrix = tf.constant([[9.,12.], 
                             [3.,2.], 
                             [8.,9.]], dtype =  tf.float16) # specify the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 9., 12.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# check the dimension of our matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
# Check the dimension of the tensor
tensor.ndim

3

***Example:***

you might turn a series of images into tensors with shape (224,224,3,32), where:
- 224,224 are the height and width of the images in pixels.
- 3 is the number of colour channels of the image (red, green, blue).
- 32 is the batch size (the number of images a neural network sees at any one time).


***Definition:***

* **Scalar**: a single number
* **Vector**: a number with direction
* **Matrix**: a 2-dimensional array of numbers
* **Tensor**: an n-dimensional array of numbers (a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector)

<center><img src="images/00-scalar-vector-matrix-tensor.png" rel="representation of vector, scalar and tensors" width=500px></center>

### Create Tensors with `tf.Variable()`

We can also create tensors using `tf.Variable()`. The difference between `tf.constant()` and `tf.Variable()`  is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where tensors created with ``tf.Variable()` are mutable (can be changed).

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

Why would you want to create random tensors?

This is what neural networks use to initialize thei weights (patterns) that they're trying to learn in the data.

**How a network learns :**
<center><img src="images/00-how-a-network-learns.png" width=650px>

<i>A network learns by starting with random patterns (1) then going through demonstrative examples of data (2), whilts trying to update its random patterns to represent the examples(3)</i></center>


In [17]:
# Create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# Create two random (but not the same) tensors

random_1 = tf.random.Generator.from_seed(6) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # create tensor from a normal distribution

random_2 = tf.random.Generator.from_seed(12)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.97061104, -1.0242516 ],
        [-0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle a tensor

In [19]:
# shuffle a tensor

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled) # shuffle along its first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [20]:
# shuffle our non_shuffled tensor

# Set the global random seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [21]:
# Exercice: Test global level random seed and operation level random seed

tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level  random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [22]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=7) # operation level  random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

### Other ways to make tensors 

Create tensor of ones with `tf.ones()` and create tensor of zeros with `tf.zeros()`

In [23]:
# Create a tensor of all ones
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor of all zeros
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [25]:
# Turn NumPy arrays into tensors
import numpy as np

numpy_A = np.arange(1,10,dtype=np.int32)
A = tf.constant(numpy_A,shape=(3,3))

numpy_A, A


(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>)

### Getting information froms tensors(shape, rank, size)

**Tensor vocabulary:**
* **Shape:** The length (number of elements) of each of the dimensions of a tensor.
* **Rank:** The number of tensor dimensions. A scalar has rank 0, vector rank 1, matrix is rank 2, and a tensor has a rank n.
* **Axis** or **Dimension:** A particular dimension of a tensor
* **Size:** The total number of items in the tensor

In [27]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros((2,3,4,5))
rank_4_tensor,rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4)

In [29]:
# shape, rank, size
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [37]:
# Get various attributes of our tensor
print("Datetype of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datetype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [44]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [45]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[12,2],[4,22]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  2],
        [ 4, 22]])>,
 TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [52]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 22])>

You can also add dimensions to your tensor whilst keeping the same information present using `tf.newaxis`

In [54]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]  # in Python "..." means "all dimensions prior to"
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 2]],

       [[ 4],
        [22]]])>

You can achieve the same using `tf.expand_dims()`

In [56]:
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means last axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 2]],

       [[ 4],
        [22]]])>

In [57]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[12,  2],
        [ 4, 22]]])>

### Manipulating tensors

**Basic operations**

`+`, `-`, `/`, `*`

In [58]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [59]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [65]:
# Multiplication (element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [61]:
# Substraction 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [62]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

You can also use the equivalent TensorFlow function. Using the TensorFlow function has the advantage of being speed up later down the line when running as part of a `TensorFlow graph`.

In [63]:
# Use the tensorflow function equivalent of the '*' 
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [64]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

### Matrix multiplication

One of the most common operations in machine learning algorithms is `matrix multiplication`.

TensorFlow implements this matrix multiplication funtionality in the `tf.matmul()` method.

The main two rules for matrix multiplications to remember are:

1. The inner dimensions must match:
    - `(3,5) @ (3,5)` won't work
    - `(5,3) @ (3,5)` will work
    - `(3,5) @ (5,3)` will work
2. The resulting matrix has the shape of the outer dimensions:
    - `(5,3) @ (3,6)` -> `(5,6)`
    - `(3,5) @ (5,3)` -> `(3,3)`

**🔑 Note:** '@' in Python is the symbol for matrix multiplication

In [68]:
# Matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [69]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [73]:
# Example
tensor1 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])
tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])

print("Shape:",tensor1.shape,tensor2.shape)

# Matrix multiplication tensorflow
result = tf.matmul(tensor1,tensor2)
print("Matrix multiplication tensorflow:",result)

# Matrix multiplication python operato
result2 = tensor1 @ tensor2
print("Matrix multiplication python:", result2)

Shape: (3, 3) (3, 2)
Matrix multiplication tensorflow: tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)
Matrix multiplication python: tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


In [75]:
# Create a (3,2) tensor X

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) tensor Y
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [77]:
# Try matrix multiplication of tensors of same shape
tf.matmul(X,Y)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

Trying to matrix multiply two tensors with the shame shape will cause an error because the inner dimensions don't match. We need to either:
- Reshape X to `(2,3)` so it's `(2,3) @ (3,2)`
- Reshape Y to `(3,2)` so it's `(2,3) @ (3,2)`

We can do this with :
- `tf.reshape()` -> allows us to reshape a tensor into a defined shape
- `tf.transpose()` - switches the dimensions of a given tensor

<center><img src="images/00-lining-up-dot-products.png" width=650px></center>

**tf.reshape()**

In [92]:
# X and Y shape
print("X & Y shape:",X.shape,Y.shape)

# reshape Y
Y_reshape = tf.reshape(Y,shape=(Y.shape[1],Y.shape[0])) # or tf.reshape(Y,shape=(2,3))
print("X & Y reshape:",X.shape,Y_reshape.shape)

# Matrix multiplication
print("Matrix mult X @ Y_reshape:",tf.matmul(X,Y_reshape))

X & Y shape: (3, 2) (3, 2)
X & Y reshape: (3, 2) (2, 3)
Matrix mult X @ Y_reshape: tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


**tf.transpose()**

In [98]:
# X & Y shape
print("X & Y shape:",X.shape, Y.shape)

# Y transpose
Y_transpose = tf.transpose(Y)
print("Y transpose:",Y_transpose)

# Matrix multiplication X and Y transpose
print("Matrix mult X @ Y.T:", tf.matmul(X,Y_transpose))

X & Y shape: (3, 2) (3, 2)
Y transpose: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
Matrix mult X @ Y.T: tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)


### The dot product

You can perform the `tf.matmul()` operation using `tf.tensordot()`.

In [107]:
# Perform the dot product on X and Y 
print("X & Y shape:",X.shape,Y.shape)
print(X,tf.transpose(X),Y)

# X or y need to be transpose or reshape
tf.tensordot(tf.transpose(X),Y,axes=1)

X & Y shape: (3, 2) (3, 2)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [110]:
# Matrix multiplication with X transposed
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [113]:
# Matrix multiplication with X reshaped
tf.tensordot(tf.reshape(X,shape=(2,3)),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

Calling `tf.transpose()` and `tf.reshape()` on `X` don't necessarily result in the  same values.

In [117]:
print("X:",X,end="\n\n")
print("X transposed:", tf.transpose(X),end="\n\n")
print("X reshaped:",tf.reshape(X,shape=(X.shape[1],X.shape[0])))

X: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

X transposed: tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)

X reshaped: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


As we can see, the outputs of `tf.reshape()` and `tf.transpose()` when we called on X, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:
- `tf.reshape()` - change the shape of the given tensor and then insert values in order they appear
- `tf.transpose()` - swap the order of the axes, by default the last axis becomes the first

### Changing the datatype of a tensor

In [119]:
# Create a new tensor with default datatype

A = tf.constant([1.3,7,5])
A.dtype

tf.float32

In [120]:
B = tf.constant([1,2,3])
B.dtype

tf.int32

You can change the datatype of a tensor using `tf.cast()`

In [121]:
C = tf.cast(B,dtype=tf.float16)
C

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

In [122]:
D = tf.cast(A,dtype=tf.int16)
D

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 7, 5], dtype=int16)>

### Tensor Aggregation (finding the min, max, mean & more)

We can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, or maximum values of all the elements.

To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
- `tf.reduce_min()` - find the minimum value in a tensor.
- `tf.reduce_max()` - find the maximum value in a tensor.
- `tf.reduce_mean()` - find the mean of all elements in a tensor.
- `tf.reduce_sum()` - find the sum of all elements in a tensor.

**Getting the absolute values**

In [123]:
# Getting the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [124]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

**Finding the min, max, mean, sum**

In [139]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([56, 22, 91, 70, 55, 86,  8,  9, 26, 46, 13, 65, 96, 37, 66, 91, 22,
       92, 22, 96, 79, 29, 66, 77, 63, 48, 70, 58, 80, 21, 26, 15, 56, 27,
       76, 32, 25, 53, 64, 11, 94, 86,  7, 10, 14, 67, 22, 37,  2, 44])>

In [140]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [141]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [142]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [143]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2428>

In [146]:
# Find the variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=827.5>

In [148]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.77>

### Finding the positional maximum and minimum