# 00 - Getting started with Tensorflow

## 1. Introduction to Deep Learning

### What is deep learning?

Artificial intelligence is a field that is trying to get a computer to think for itself. Then Machine learning is turning things (data) into number and <b>finding patterns</b> in those numbers. Deep learning is a subfield of machine Learning. 

<center><img rel="slide ML vs DL" src="images/00-ml-vs-dl.png" heigth=200px width=600px></center>

### Why use deep learning?

<b>Better reason :</b> For a complex problem, can you think of all the rules you'd have to code? Probably not... For example driving a car requires to follow a lot of rules (signs, pedestrian, other cars...)

**When use machine learning ?**

- rule 1 of Google's Machine Learning Handbook: "If you can build a ***simple rule-based*** system that doesn't require machine learning, do that."



### What deep learning is good for ?


- **Problems with long lists of rules** : when the traditional approach fails, machine learning/deep learning may help.
- **Continually changing environments** : deep learning can adapt("learn") to new scenarios.
- **Discovering insights within large collections of data** : can you imagine trying to hand-craft rules for what 101 different kinds of food look like?

### What deep learning is not good for ?


- **When you need explainability** : the patterns learned by a deep learning model are typically uninterpretable by a human.
- **When the traditional approach is a better option** : if you can accomplish what you need with a simple rule-based system.
- **When errors are unacceptable** : since the outputs of deep learning model aren't always predictable.
- **When you don't have much data** : deep learning models usually require a fairly amount of data to produce great results

### What are neural networks?

**Examples of uses :**

<center><img rel="slide ML vs DL" src="images/00-neural-networks.png" heigth=200px width=800px></center>


**Anatomy of Neural Networks :**

<center><img rel="slide ML vs DL" src="images/00-anatomy-neural-networks.png" heigth=200px width=800px></center>

### What is deep learning already being used for?

<center><img rel="slide ML vs DL" src="images/00-deeplearning-use-cases.png" heigth=200px width=800px></center>

## 2. Tensorflow Fundamentals

### What is Tensorflow?

`Tensorflow` is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

### Why use TensorFlow?

Rather than building machine learning and deep learning models from scratch, it's more likely you'll use a library such as Tensorflow. This is because it contains many of the most common machine learning functions we'll want to use.

### Introduction to Tensors

`Tensors` are kind of Numpy arrays.

You can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:
- It could be numbers themselves (using tensors to represent the price of house).
- It could be an image (using tensors to represent the pixels of an image).
- It could be text (using tensors to represent words).
- Or it could be some other form of information (or data) you want to represent with numbers.

The main difference between tensors and NumPy arrays is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).
The benefit of being able to run on GPUs and TPUs is faster computation. This means if we wanted to find patterns in the numerical representations of our data, we can find them faster using GPUs and TPUs.

In [1]:
# import TensorFlow

import tensorflow as tf
print (tf.__version__) # find the version number

2.8.0


### Creating Tensors with `tf.constant()`

In [2]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [8]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
# Check the dimension of our matrix
matrix.ndim

2

By default, TensorFlow creates tensors with either an `int32` or `float32` datatype. This is known as 32-bit precision.

In [13]:
# Create another matrix and define the datatype

another_matrix = tf.constant([[9.,12.], 
                             [3.,2.], 
                             [8.,9.]], dtype =  tf.float16) # specify the data type

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 9., 12.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [24]:
# check the dimension of our matrix
another_matrix.ndim

2

In [26]:
# Let's create a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [27]:
# Check the dimension of the tensor
tensor.ndim

3

***Example:***

you might turn a series of images into tensors with shape (224,224,3,32), where:
- 224,224 are the height and width of the images in pixels.
- 3 is the number of colour channels of the image (red, green, blue).
- 32 is the batch size (the number of images a neural network sees at any one time).


***Definition:***

* **Scalar**: a single number
* **Vector**: a number with direction
* **Matrix**: a 2-dimensional array of numbers
* **Tensor**: an n-dimensional array of numbers (a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector)

<center><img src="images/00-scalar-vector-matrix-tensor.png" rel="representation of vector, scalar and tensors" width=500px></center>

### Create Tensors with `tf.Variable()`