# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3.3],[4,5.2,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]]])

a1,a2,a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5.2, 6. ]]),
 array([[[1, 2, 3],
         [4, 5, 6]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.size, a1.ndim, a1.dtype, type(a1)

((3,), 3, 1, dtype('int32'), numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.shape, a2.size, a2.ndim, a2.dtype, type(a2)

((2, 3), 6, 2, dtype('float64'), numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.shape, a3.size, a3.ndim, a3.dtype, type(a3)

((1, 2, 3), 6, 3, dtype('int32'), numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2, columns=["A","B","C"])
df

A    B    C
0  1.0  2.0  3.3
1  4.0  5.2  6.0

In [11]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,size=(7,2))

array([[7, 7],
       [0, 5],
       [1, 7],
       [1, 5],
       [9, 4],
       [7, 1],
       [7, 3]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.00706631, 0.02306243, 0.52477466, 0.39986097, 0.04666566],
       [0.97375552, 0.23277134, 0.09060643, 0.61838601, 0.38246199],
       [0.98323089, 0.46676289, 0.85994041, 0.68030754, 0.45049925]])

In [23]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr1 = np.random.randint(1,10,size=(3,7))
print(arr1)
# Find the unique numbers in the array you just created
np.unique(arr1)

[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Find the 0'th index of the latest array you created
arr1[0]

array([9, 1, 3, 7, 4, 9, 3])

In [27]:
# Get the first 2 rows of latest array you created
arr1[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [28]:
# Get the first 2 values of the first 2 rows of the latest array
arr1[:2,:2]

array([[7, 8],
       [4, 2]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0,10,size=(3,5))
ones_array = np.ones((3,5))

print(random_array)
print(ones_array)

[[6 7 4 2 7]
 [5 2 0 2 4]
 [2 0 4 9 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
# Add the two arrays together
random_array + ones_array

array([[ 5.,  8., 10.,  9.,  9.],
       [ 1.,  9.,  7.,  9.,  8.],
       [ 1.,  8.,  8.,  3.,  1.]])

In [34]:
# Create another array of ones of shape (5, 3)
ones_array2 = np.ones((5,3))
ones_array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# Try add the array of ones and the other most recent array together
random_array + ones_array2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [36]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [37]:
# Subtract the new array of ones from the other most recent array
ones - random_array

array([[-5., -6., -3., -1., -6.],
       [-4., -1.,  1., -1., -3.],
       [-1.,  1., -3., -8., -5.]])

In [38]:
# Multiply the ones array with the latest array
ones * random_array

array([[6., 7., 4., 2., 7.],
       [5., 2., 0., 2., 4.],
       [2., 0., 4., 9., 6.]])

In [39]:
# Take the latest array to the power of 2 using '**'
random_array**2

array([[36, 49, 16,  4, 49],
       [25,  4,  0,  4, 16],
       [ 4,  0, 16, 81, 36]], dtype=int32)

In [40]:
# Do the same thing with np.square()
np.square(random_array)

array([[36, 49, 16,  4, 49],
       [25,  4,  0,  4, 16],
       [ 4,  0, 16, 81, 36]], dtype=int32)

In [41]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.0

In [42]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

9

In [43]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

0

In [44]:
# Find the standard deviation of the latest array
np.std(random_array)

2.581988897471611

In [45]:
# Find the variance of the latest array
np.var(random_array)

6.666666666666667

In [47]:
# Reshape the latest array to (3, 5, 1)
random_array.reshape((3,5,1))

array([[[6],
        [7],
        [4],
        [2],
        [7]],

       [[5],
        [2],
        [0],
        [2],
        [4]],

       [[2],
        [0],
        [4],
        [9],
        [6]]])

In [48]:
# Transpose the latest array
random_array.T

array([[6, 5, 2],
       [7, 2, 0],
       [4, 0, 4],
       [2, 2, 9],
       [7, 4, 6]])

What does the transpose do?

In [49]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1 = np.random.randint(0,10,size=(3,3))
mat2 = np.random.randint(0,10,size=(3,2))

In [50]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

array([[126,  78],
       [ 84,  72],
       [ 36,  15]])

In [51]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat1 = np.random.randint(0,10,size=(4, 3))
mat2 = np.random.randint(0,10,size=(4, 3))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [54]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(mat1,mat2.T)

array([[ 80,  41,  98,  44],
       [ 72,  66, 103,  80],
       [120,  93, 105,  60],
       [ 48,  72,  78,  88]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat1 = np.random.randint(0,10,size=(4, 3))
mat2 = np.random.randint(0,10,size=(4, 3))
print(mat1,mat2,sep="\n\n")

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]

[[6 1 7]
 [0 8 8]
 [1 6 9]
 [2 6 9]]


In [59]:
# Compare the two arrays with '>'
mat1 > mat2

array([[False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [60]:
# Compare the two arrays with '>='
mat1 >= mat2

array([[False,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False, False]])

In [62]:
# Find which elements of the first array are greater than 7
print(mat1)
print(mat1>7)
print(mat1[mat1>7])

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]
[[False False False]
 [ True False False]
 [False False False]
 [ True False False]]
[9 8]


In [63]:
# Which parts of each array are equal? (try using '==')
mat1 == mat2

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [66]:
# Sort one of the arrays you just created in ascending order
print(mat1)
np.sort(mat1)

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]


array([[2, 3, 3],
       [2, 2, 9],
       [3, 3, 6],
       [0, 7, 8]])

In [67]:
# Sort the indexes of one of the arrays you just created
print(mat1)
np.argsort(mat1)

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]


array([[2, 0, 1],
       [1, 2, 0],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [68]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat1)

3

In [69]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat1)

10

In [74]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(mat1)
np.argmax(mat1,axis=1), np.max(mat1,axis=1)

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]


(array([0, 0, 1, 0], dtype=int64), array([3, 9, 6, 8]))

In [78]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(mat1)
np.argmax(mat1,axis=0), np.max(mat1,axis=0)

[[3 3 2]
 [9 2 2]
 [3 6 3]
 [8 0 7]]


(array([1, 2, 3], dtype=int64), array([9, 6, 7]))

In [79]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.0130339 ,  0.37776959,  0.0628246 ,  0.50159637, -0.14694539],
       [ 0.18062297,  0.96481058, -1.06483115,  0.1087118 ,  0.10576365],
       [ 0.92066672, -0.22672246,  0.65304831,  1.10268747, -1.84980294]])

In [80]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.